hydra:
  run:
    dir: .

data:
  train_path: /dtu/datasets1/imagenet_object_localization_patched2019/ILSVRC/Data/CLS-LOC/train
  val_path: /dtu/datasets1/imagenet_object_localization_patched2019/ILSVRC/Data/CLS-LOC/val
  img_size: 224

model:
  name: mae_vit_base_patch16
  norm_pix_loss: true

experiment:
  name: pretrain_in1k_0.75_800
  seed: 42

training:
  epochs: 800
  learning_rate: 0.003 # (base_lr (5e-4) * batch_size (1024) * num_gpus (2)) / 256
  batch_size: 768
  num_workers: 4
  check_val_every_n_epoch: 10
  overfit_batches: 0 # Use all data
  
optimizer:
  name: adamw
  beta1: 0.9
  beta2: 0.95
  weight_decay: 0.05

scheduler:
  warmup_epochs: 40

compute:
  accelerator: gpu
  devices: 2

mae:
  mask_ratio: 0.75

resume_from_checkpoint: